version: '3.7'
services:
  openjdk:
    build: .
    container_name: openjdk-15-jdk-slim-buster
    environment:
      TZ: Asia/Shanghai
    image: v8fg/openjdk:15-jdk-slim-buster
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
