version: '3.7'
services:
  nginx:
    build: .
    container_name: nginx-latest
    environment:
      TZ: Asia/Shanghai
      # NGINX_HOST: foobar.com
      NGINX_PORT: 8080
    image: v8fg/nginx:latest
    stdin_open: true
    tty: true
    volumes: 
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    # command: [ "/bin/bash"]
    command: [nginx-debug, '-g', 'daemon off;']
