version: '3.7'
services:
  mysql:
    build: .
    container_name: mysql-latest
    environment:
      TZ: Asia/Shanghai
    image: v8fg/mysql:latest
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
