version: '3.7'
services:
  kafka:
    build: .
    container_name: kafka-latest
    environment:
      TZ: Asia/Shanghai
    image: v8fg/kafka:latest
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
